# -*- coding: utf-8 -*-
"""Problem 996a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwZgP97KwfrQ6yNnjkcTsizPFmH6hiQ9
"""

# Verifies if bill divided by money is 0, if so, money is reduced to the rest
# of division value, and adds count to the quantity of bills used.
# Stops loop if money equals 0.
# Outputs number of bills used.

# Verifies if bill divided by money is 0, if so, money is reduced to the rest
# of division value, and adds count to the quantity of bills used.
# Stops loop if money equals 0.
# Outputs number of bills used.

def divide_money(money):
  bills = [1, 5, 10, 20, 100]

  bills.sort(reverse=True) # makes sure its in decreasing order

  quantity_of_bills = 0

  for bill in bills:
    count = money // bill
    quantity_of_bills += count

    money = money % bill

    if money == 0:
      break

  return quantity_of_bills

# Commented because of problem with input in codeforce
    
# money = int(input("Money: "))

# print(divide_money(money))
