# -*- coding: utf-8 -*-
"""Problem 226A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAVPMwuyN_DsoRc2Wwm9uUYEc5UhXXCh
"""

def neighbor_stones(number_of_stones, stone_colors):
  colors = ['R', 'G', 'B']
  count = 0

  if len(stone_colors) != number_of_stones:
    print("Error: different number of colors from number of stones")
  else:
    for c in stone_colors:
      if c not in colors:
        print(f"Invalid color: {c}")


  for i in range(len(stone_colors) - 1):
    if stone_colors[i] == stone_colors[i+1]:
      count += 1
  return count

number_of_stones = int(input())
stone_colors = input()

print(neighbor_stones(number_of_stones, stone_colors))