# -*- coding: utf-8 -*-
"""Problem 4A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m4HTRdLHAB6ZnswvPYL6c8vibZR1vBuw

https://codeforces.com/problemset/problem/4/A
"""

watermelon_weight = int(input())

if watermelon_weight % 2 == 0 and watermelon_weight > 2:
  print("YES")
else:
  print("NO")